" Basics.
set nocompatible
set encoding=utf-8

" This is where we'll use pathogen / vundle to load packages.
let &runtimepath.=','.expand('<sfile>:p:h')
runtime packages/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect('packages/{}')

" Get the right colors
set t_Co=256
set background=dark

" Reselect visual block after indent/outdent.
vnoremap < <gv
vnoremap > >gv

" Set leader stuff.
let mapleader=','

" Use after to set stuff that needs to be done on load.
autocmd VimEnter * :CSApprox
autocmd VimEnter * :colorscheme base16-default
